## Tensorの基礎

In [22]:
# pytouchをインポート
import torch
import numpy as np

# 乱数の固定(tensor)
torch.manual_seed(42)

# 乱数の固定(numpy)
# np.random.seed(0)

In [3]:
# Tensor作成
my_list = [1,2,3,4]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1, 2, 3, 4])

In [4]:
# タイプを確認
type(tensor_from_list)

torch.Tensor

In [5]:
# dtypeを確認
tensor_from_list.dtype

torch.int64

In [6]:
# floatにしてみる
my_list = [1.,2.,3.,4.]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1., 2., 3., 4.])

In [9]:
# デフォルトでfloat32
tensor_from_list.dtype


torch.float32

In [10]:
# float64に指定する
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [17]:
# すでに用意されている特別なtensor(配列)
# numpyと同じ感じ
zeros_tensor = torch.zeros((2, 3))

In [12]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
ones_tensor = torch.ones((2, 3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
eye_tensor = torch.eye(3)
eye_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
random_tensor = torch.rand((2, 3))
random_tensor

tensor([[0.8519, 0.1800, 0.4975],
        [0.8483, 0.4840, 0.7842]])

In [20]:
# 型を確認
random_tensor.dtype

torch.float32

In [24]:
# まとめ(tensor)
zeros_tensor = torch.zeros((2, 3))
ones_tensor = torch.ones((2, 3))
eye_tensor = torch.eye(3)
random_tensor = torch.rand((2, 3))

print(zeros_tensor, zeros_tensor.dtype)
print(ones_tensor, ones_tensor.dtype)
print(eye_tensor, eye_tensor.dtype)
print(random_tensor, random_tensor.dtype)


tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) torch.float32
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]]) torch.float32


In [27]:
# まとめ(numpy)
np_zeros = np.zeros((2,3))
np_ones = np.ones((2, 3))
np_eye = np.eye(3)
# tensorと違って、random.randになる
np_random = np.random.rand(2, 3)

print(np_zeros, np_zeros.dtype)
print(np_ones, np_ones.dtype)
print(np_eye, np_eye.dtype)
print(np_random, np_random.dtype)

# numpyのデータ型のデフォルトはfloat64

[[0. 0. 0.]
 [0. 0. 0.]] float64
[[1. 1. 1.]
 [1. 1. 1.]] float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64
[[0.17304687 0.18939991 0.5125553 ]
 [0.47331304 0.12394428 0.22148253]] float64


In [30]:
# shapeを確認
zeros_tensor.shape

# 出力はリストみたいになっているけど、タプルで出力される

torch.Size([2, 3])

In [31]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
# これもタプルで出力される
np_zeros.shape

(2, 3)