## Tensorの基礎

In [1]:
# pytouchをインポート
import torch
import numpy as np

# 乱数の固定(tensor)
torch.manual_seed(42)

# 乱数の固定(numpy)
# np.random.seed(0)

In [3]:
# Tensor作成
my_list = [1,2,3,4]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1, 2, 3, 4])

In [4]:
# タイプを確認
type(tensor_from_list)

torch.Tensor

In [5]:
# dtypeを確認
tensor_from_list.dtype

torch.int64

In [6]:
# floatにしてみる
my_list = [1.,2.,3.,4.]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1., 2., 3., 4.])

In [9]:
# デフォルトでfloat32
tensor_from_list.dtype


torch.float32

In [10]:
# float64に指定する
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [17]:
# すでに用意されている特別なtensor(配列)
# numpyと同じ感じ
zeros_tensor = torch.zeros((2, 3))

In [12]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
ones_tensor = torch.ones((2, 3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
eye_tensor = torch.eye(3)
eye_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
random_tensor = torch.rand((2, 3))
random_tensor

tensor([[0.8519, 0.1800, 0.4975],
        [0.8483, 0.4840, 0.7842]])

In [20]:
# 型を確認
random_tensor.dtype

torch.float32

In [24]:
# まとめ(tensor)
zeros_tensor = torch.zeros((2, 3))
ones_tensor = torch.ones((2, 3))
eye_tensor = torch.eye(3)
random_tensor = torch.rand((2, 3))

print(zeros_tensor, zeros_tensor.dtype)
print(ones_tensor, ones_tensor.dtype)
print(eye_tensor, eye_tensor.dtype)
print(random_tensor, random_tensor.dtype)


tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) torch.float32
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]]) torch.float32


In [27]:
# まとめ(numpy)
np_zeros = np.zeros((2,3))
np_ones = np.ones((2, 3))
np_eye = np.eye(3)
# tensorと違って、random.randになる
np_random = np.random.rand(2, 3)

print(np_zeros, np_zeros.dtype)
print(np_ones, np_ones.dtype)
print(np_eye, np_eye.dtype)
print(np_random, np_random.dtype)

# numpyのデータ型のデフォルトはfloat64

[[0. 0. 0.]
 [0. 0. 0.]] float64
[[1. 1. 1.]
 [1. 1. 1.]] float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64
[[0.17304687 0.18939991 0.5125553 ]
 [0.47331304 0.12394428 0.22148253]] float64


In [30]:
# shapeを確認
zeros_tensor.shape

# 出力はリストみたいになっているけど、タプルで出力される

torch.Size([2, 3])

In [31]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
# これもタプルで出力される
np_zeros.shape

(2, 3)

## Tensorの操作

In [4]:
# 3*4の配列、テンサーが2個ある
tensor_example = torch.rand((2,3, 4))
np_example = np.random.rand(2, 3, 4)
print(tensor_example, np_example)

tensor([[[0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447]],

        [[0.5315, 0.1587, 0.6542, 0.3278],
         [0.6532, 0.3958, 0.9147, 0.2036],
         [0.2018, 0.2018, 0.9497, 0.6666]]]) [[[0.82898321 0.08410877 0.84197546 0.85939948]
  [0.86769265 0.39994034 0.94492478 0.71500793]
  [0.26872036 0.01126937 0.44190327 0.72981896]]

 [[0.80441511 0.40704454 0.16137902 0.25744768]
  [0.42094129 0.38336408 0.37023294 0.37958161]
  [0.53582301 0.16554663 0.38664678 0.99661941]]]


In [7]:
tensor_example.shape

torch.Size([2, 3, 4])

In [8]:
# 3*4のtensorが2個ある
tensor_example

tensor([[[0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447]],

        [[0.5315, 0.1587, 0.6542, 0.3278],
         [0.6532, 0.3958, 0.9147, 0.2036],
         [0.2018, 0.2018, 0.9497, 0.6666]]])

In [9]:
# 3*4が2個ある
np_example

array([[[0.82898321, 0.08410877, 0.84197546, 0.85939948],
        [0.86769265, 0.39994034, 0.94492478, 0.71500793],
        [0.26872036, 0.01126937, 0.44190327, 0.72981896]],

       [[0.80441511, 0.40704454, 0.16137902, 0.25744768],
        [0.42094129, 0.38336408, 0.37023294, 0.37958161],
        [0.53582301, 0.16554663, 0.38664678, 0.99661941]]])

In [10]:
np_example.shape

(2, 3, 4)

In [11]:
# 転値
# (0,1,2)は何も変わらず。左から０次元目、１次元目...というふうになっているから同じ形になる。
torch.permute(tensor_example, (0, 1, 2))



tensor([[[0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447]],

        [[0.5315, 0.1587, 0.6542, 0.3278],
         [0.6532, 0.3958, 0.9147, 0.2036],
         [0.2018, 0.2018, 0.9497, 0.6666]]])

In [20]:
# 転値
# これは、順番を変えたのでtensor_exampleから見ると, (3, 2, 4)になる。
permuted_temsor = torch.permute(tensor_example, (1,0,2))
transposed_np = np.transpose(np_example, (1, 0, 2))
print(permuted_temsor.shape)
print(transposed_np.shape)

transposed_tensor = torch.transpose(tensor_example, 0,1)
print(transposed_tensor.shape)

torch.Size([3, 2, 4])
(3, 2, 4)
torch.Size([3, 2, 4])


In [16]:
permuted_temsor.shape

torch.Size([3, 2, 4])

In [21]:
# reshape

In [26]:
reshaped_tensor = torch.reshape(tensor_example, (6, 4))
reshaped_np = np.reshape(np_example, (6, 4))
print(reshaped_tensor.shape)
print(reshaped_np.shape)

torch.Size([6, 4])
(6, 4)


In [27]:
# reshapeはメモリを参照しているため、reshapeされたtensorを変更すると、もとのtensorも変更される
# コピーを渡しているわけではない
reshaped_tensor

tensor([[0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666]])

In [29]:
tensor_example

tensor([[[0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447]],

        [[0.5315, 0.1587, 0.6542, 0.3278],
         [0.6532, 0.3958, 0.9147, 0.2036],
         [0.2018, 0.2018, 0.9497, 0.6666]]])

In [44]:
# 同じメモリを参照していることを確かめる
reshaped_tensor[0] = 0
reshaped_tensor

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666]])

In [43]:
# tensor_examplehは何もいじっていないのに、変わっている！
tensor_example

tensor([[[0.0000, 0.0000, 0.0000, 0.0000],
         [0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447]],

        [[0.5315, 0.1587, 0.6542, 0.3278],
         [0.6532, 0.3958, 0.9147, 0.2036],
         [0.2018, 0.2018, 0.9497, 0.6666]]])

In [28]:
reshaped_np

array([[0.82898321, 0.08410877, 0.84197546, 0.85939948],
       [0.86769265, 0.39994034, 0.94492478, 0.71500793],
       [0.26872036, 0.01126937, 0.44190327, 0.72981896],
       [0.80441511, 0.40704454, 0.16137902, 0.25744768],
       [0.42094129, 0.38336408, 0.37023294, 0.37958161],
       [0.53582301, 0.16554663, 0.38664678, 0.99661941]])

In [32]:
# メモリが連続でなければreshapeはコピーを返す
x = torch.tensor(([1,2], [3, 4], [5, 6]))
x

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [33]:
y = x.T
y 

tensor([[1, 3, 5],
        [2, 4, 6]])

In [36]:
# 先ほどのyは連続なメモリに保存されていない
# メモリが連続であるかをboolで判断
print(y.is_contiguous())
print(x.is_contiguous())

False
True


In [37]:
z = y.reshape(-1)

In [38]:
z

tensor([1, 3, 5, 2, 4, 6])

In [39]:
y

tensor([[1, 3, 5],
        [2, 4, 6]])

In [40]:
# このzとyは同じメモリを見ているわけではない
z[0] = 0
z

tensor([0, 3, 5, 2, 4, 6])

In [41]:
y

tensor([[1, 3, 5],
        [2, 4, 6]])

In [68]:
# 実際にメモリを連続で判断するとかしていないよ！ -> torch.view()を使う
# コピーを返して欲しくない(同じメモリを使う) -> メモリを節約したい, 厳密にメモリを管理したい -> reshapeではなくて、torch.view()を使う
# そうでなくて、とりあえずreshapeしたいというときは、reshapeでもいい

In [69]:
# flatten(多次元配列を１次元、１rankにする)
flatten_tensor = torch.flatten(tensor_example)
flatten_np = np_example.flatten()
print(flatten_tensor.shape)
print(flatten_np.shape)



torch.Size([3])
(3,)


In [70]:
tensor_example.shape

torch.Size([1, 3, 1])

In [71]:
flatten_tensor

tensor([1, 2, 3])

In [72]:
# squeeze
tensor_example = torch.tensor([[[1],[2], [3]]])
np_example = np.array([[[1], [2], [3]]])
print(tensor_example.shape)
print(np_example.shape)

torch.Size([1, 3, 1])
(1, 3, 1)


In [73]:
tensor_example

tensor([[[1],
         [2],
         [3]]])

In [74]:
np_example

array([[[1],
        [2],
        [3]]])

In [75]:
# 次元が1の部分を削除した
squeezed_tensor = torch.squeeze(tensor_example)
squeezed_np = np.squeeze(np_example)
print(squeezed_tensor.shape)
print(squeezed_np.shape)

torch.Size([3])
(3,)


In [79]:
# 最初の部分に次元が追加された
unsqueezed_tensor = torch.unsqueeze(tensor_example, 0)
# squeezed_np = np.squeeze(np_example)
expand_dims_np = np.expand_dims(np_example, 0)
print(unsqueezed_tensor.shape)
print(expand_dims_np.shape)

torch.Size([1, 1, 3, 1])
(1, 1, 3, 1)


In [77]:
squeezed_tensor

tensor([1, 2, 3])

In [80]:
# squeezeやunsqueezeを使って次元を調整するのはよくある


### Tensorの便利関数

In [83]:
tensor_example = torch.rand((2, 3))
np_example = np.random.rand(2, 3)

# 疑問
# torch.rand(2, 3)とtorch.rand((2, 3))は何が違うのか？

In [84]:
tensor_example

tensor([[0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025]])

In [87]:
np_example

array([[0.14648123, 0.23668738, 0.99116782],
       [0.66555702, 0.74162183, 0.71477484]])

In [91]:
# 合計
print(torch.sum(tensor_example))
print(np.sum(np_example))

# 平均
print(torch.std(tensor_example))
print(np.std(np_example))

# 標準偏差
print(torch.std(tensor_example))
print(np.std(np_example))

# もとの行列の値をすべてrootを取る
print(torch.sqrt(tensor_example))
print(np.sqrt(np_example))

tensor(2.0475)
3.496290124970787
tensor(0.4009)
0.29620451978529305
tensor(0.4009)
0.29620451978529305
tensor([[0.9905, 0.2956, 0.0637],
        [0.3299, 0.4045, 0.8382]])
[[0.38272866 0.48650527 0.99557412]
 [0.81581678 0.86117468 0.84544358]]


In [93]:
# これはtensorを返す。値だけを返すのではない。
torch.sum(tensor_example)

# 値だけ返すものは.item()をつける。リストに格納したいとかっていう時によく使う。
torch.sum(tensor_example).item()

2.0475428104400635

### 行列の演算

#### 加減算,要素ごとの乗除算

In [95]:
a = torch.rand((3, 3))
b = torch.rand((3, 3))
print(a)
print(b)

tensor([[0.4340, 0.1371, 0.5117],
        [0.1585, 0.0758, 0.2247],
        [0.0624, 0.1816, 0.9998]])
tensor([[0.5944, 0.6541, 0.0337],
        [0.1716, 0.3336, 0.5782],
        [0.0600, 0.2846, 0.2007]])


In [97]:
# 要素ごとの足し算 ex) 0.434 + 0.5944 = 1.0284
a + b

tensor([[1.0284, 0.7911, 0.5454],
        [0.3301, 0.4094, 0.8029],
        [0.1224, 0.4662, 1.2005]])

In [98]:
a - b

tensor([[-0.1604, -0.5170,  0.4781],
        [-0.0132, -0.2578, -0.3535],
        [ 0.0024, -0.1029,  0.7991]])

In [99]:
a * b

tensor([[0.2580, 0.0896, 0.0172],
        [0.0272, 0.0253, 0.1299],
        [0.0037, 0.0517, 0.2006]])

In [100]:
a / b

tensor([[ 0.7301,  0.2095, 15.2038],
        [ 0.9234,  0.2272,  0.3886],
        [ 1.0392,  0.6383,  4.9824]])

In [101]:
# 行列の積
# 行列は交換法則は成り立たない。この場合は、左に対して右から行列をかけている。
torch.mm(a, b)

tensor([[0.3122, 0.4752, 0.1965],
        [0.1207, 0.1929, 0.0942],
        [0.1283, 0.3859, 0.3077]])

In [102]:
torch.matmul(a, b)

tensor([[0.3122, 0.4752, 0.1965],
        [0.1207, 0.1929, 0.0942],
        [0.1283, 0.3859, 0.3077]])

In [103]:
# torch.mm(a, b)とtorch.matmul(a, b)と a @ bも同じ
a @ b

tensor([[0.3122, 0.4752, 0.1965],
        [0.1207, 0.1929, 0.0942],
        [0.1283, 0.3859, 0.3077]])

In [106]:


# スカラー: ランク0
scalar = np.array(5)  

# ベクトル: ランク1 (例えば、3要素)
vector = np.array([1, 2, 3])

# 行列: ランク2 (例えば、2x3)
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# 3Dテンソル: ランク3 (例えば、2x3x4)
tensor_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                      [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])


In [108]:
scalar

array(5)

In [109]:
vector

array([1, 2, 3])

In [110]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
tensor_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [112]:
print(scalar.shape)
print(vector.shape)
print(matrix.shape)
print(tensor_3d.shape)

()
(3,)
(2, 3)
(2, 3, 4)


In [118]:
# 次元数
tensor_3d.ndim

3

array([[1, 2, 3]])

### ブロードキャスティング

In [120]:
# (3, 3)とスカラーの演算
a = torch.rand(3, 3)
scaler = 5
a

tensor([[0.5014, 0.3139, 0.4654],
        [0.1612, 0.1568, 0.2083],
        [0.3289, 0.1054, 0.9192]])

In [121]:
scaler 

5

In [122]:
# scalerがそれぞれの要素に足している
# 内部ではブロードキャスティングしている
a + scaler

tensor([[5.5014, 5.3139, 5.4654],
        [5.1612, 5.1568, 5.2083],
        [5.3289, 5.1054, 5.9192]])

In [124]:
# (3, 3)と(1, 3)の演算
b = torch.rand(1, 3)
b

tensor([[0.0766, 0.8460, 0.3624]])

In [126]:
# 次元が１, rankが同じ
a + b

tensor([[0.5780, 1.1600, 0.8278],
        [0.2378, 1.0028, 0.5707],
        [0.4055, 0.9514, 1.2817]])

In [127]:
# (32, 128, 128, 3)と(128, 128, 3)の演算
a = torch.rand((32, 128, 128, 3))
b = torch.rand((128, 128, 3))


In [130]:
a.shape

torch.Size([32, 128, 128, 3])

In [131]:
(a + b).shape

torch.Size([32, 128, 128, 3])

In [133]:
# (32, 128, 128, 3)と(128, 128, 6)の演算
a = torch.rand((32, 128, 128, 3))
b = torch.rand((128, 128, 6))
# ブロードキャスティングできない
# それぞれのtensorの演算が形状的に問題がないか、と考える必要あり
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 3

In [137]:
# (1, 128, 128, 3)と(8, 128, 128, 1)の演算
a = torch.rand((1, 128, 128, 3))
b = torch.rand((8, 128, 128, 1))
# ブロードキャスティングできない
# 実行できる
(a + b).shape

torch.Size([8, 128, 128, 3])